version: "3.8"

services:
  db:
    container_name: showerbot-db
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=showerbot
      - POSTGRES_PASSWORD=showerbot
      - POSTGRES_DB=showerbot
    volumes:
      - ./docker-volume:/var/lib/postgresql/data
    network_mode: host
    healthcheck:
      test: pg_isready -U showerbot -d showerbot
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    container_name: showerbot-amd
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    platform: linux/amd64
    image: badewanne3/showerbot:amd64
    env_file:
      - .docker.env
    volumes:
      - ./docker-volume:/var/local/showerbot
    network_mode: host
    depends_on:
      db:
        condition: service_healthy