FROM arm32v7/rust:slim-bullseye as builder

WORKDIR /build
COPY . .

RUN cargo build --release

FROM arm32v7/debian:bullseye-slim

RUN apt update && apt upgrade && apt install ca-certificates -y
COPY --from=builder /build/target/release/showerbot /usr/local/bin/showerbot

RUN touch .env && mkdir -p /usr/local/beatmaps/
WORKDIR /usr/local/showerbot/

CMD ["showerbot"]