version: "3.8"

services:
  db:
    container_name: showerbot-db
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=showerbot
      - POSTGRES_PASSWORD=showerbot
      - POSTGRES_DB=showerbot
    ports:
      - 5423:5432
    volumes:
      - ./docker-volume/psql:/var/lib/postgresql/data
    networks:
      - showerbot-net

  bot:
    container_name: showerbot
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    platform: linux/arm/v7
    image: badewanne3/showerbot:arm32
    # privileged: true
    env_file:
      - .docker.env
    volumes:
      - ./docker-volume:/var/local/showerbot
    networks:
      - showerbot-net
    depends_on:
      - db

networks:
  showerbot-net:
    driver: bridge