# https://rust-lang.github.io/rustfmt/

# condense_wildcard_suffixes = true
edition = "2021"
# error_on_unformatted = true
# fn_single_line = true
# format_code_in_doc_comments = true
# format_strings = true
newline_style = "Unix"
# reorder_impl_items = true
# group_imports = "StdExternalCrate"
use_field_init_shorthand = true
# wrap_comments = true